mealplanner/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('planner/', include('planner.urls')),
    path('', RedirectView.as_view(url='planner/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    
] 


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

planner/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('days/', views.DayListView.as_view(), name='days'),
    path('day/<int:pk>', views.DayDetailView.as_view(), name='day-detail'),
    path('meals/', views.MealListView.as_view(), name='meals'),
    path('meal/<int:pk>', views.MealDetailView.as_view(), name='meal-detail'),

    path('day/create/', views.createday, name='day-create'),
    path('day/<int:pk>/update/', views.DayUpdate.as_view(), name='day-update'),
    path('day/<int:pk>/delete/', views.DayDelete.as_view(), name='day-delete'),

    path('meal/create/', views.MealCreate.as_view(), name='meal-create'),
    path('meal/<int:pk>/update/', views.MealUpdate.as_view(), name='meal-update'),
    path('meal/<int:pk>/delete/', views.MealDelete.as_view(), name='meal-delete'),
]

planner/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Meal(models.Model):
    name = models.CharField(max_length=200)
    ingredients = models.TextField()
    

    MEALS = (
        ('v', 'Vegan'),
        ('n', 'Non-Vegan'),
    )
    meal_type = models.CharField(
        max_length=1,
        choices = MEALS,
        help_text = 'Select the type of meal'
    )

    meal_pic = models.FileField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('meal-detail', args=[str(self.id)])


class Day(models.Model):
    date_meal = models.DateField()

    DAYS = (
        ('m', 'Monday'),
        ('t', 'Tuesday'),
        ('w', 'Wednesday'),
        ('th', 'Thursday'),
        ('f', 'Friday'),
        ('sat', 'Saturday'),
        ('sun', 'Sunday'),
    )

    day_of_week = models.CharField(
        max_length = 3,
        choices = DAYS,
        help_text = 'Day of the Week',
    )

    meal = models.ManyToManyField(Meal, help_text="Choose meal for the day")
    cook = models.ForeignKey(User,on_delete=models.SET_NULL, null=True, blank=True, related_name='meals')
    class Meta:
        ordering = ['date_meal']

    def __str__(self):
        return f'{self.date_meal}, {self.day_of_week}'

    def get_absolute_url(self):
        return reverse('day-detail', args=[str(self.id)])

planner/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy 
from .models import Day, Meal
from bootstrap_datepicker_plus import DatePickerInput

class DayForm(forms.ModelForm):

    class Meta:
        model = Day
        fields = ['date_meal', 'day_of_week', 'meal']  
        meal = forms.ModelChoiceField(
            queryset = Meal.objects.all()
        )
        widgets = {
            'date_meal': DatePickerInput(format='%m/%d/%Y'),
        }

planner/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import DayForm
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

from planner.models import Meal, Day

def index(request):
    num_meals = Meal.objects.all().count()

    context = {
        'num_meals': num_meals,
    }

    return render(request, 'index.html', context=context)

class DayListView(LoginRequiredMixin, generic.ListView):
    model = Day
    paginate_by = 7

    def get_queryset(self):
      day_list = Day.objects.filter(cook=self.request.user)
      return day_list
      

class DayDetailView(LoginRequiredMixin, generic.DetailView):
    model = Day

# show all meals that this cook assigned to particular days on her calendar
class MealListView(LoginRequiredMixin, generic.ListView):
    model = Meal
    paginate_by = 10

class MealDetailView(LoginRequiredMixin, generic.DetailView):
    model = Meal

# CRUD for Day model
# class DayCreate(LoginRequiredMixin, CreateView):
#     model = Day
#     fields = ['day_of_week', 'date_meal', 'meal']

@login_required
def createday(request):
    if request.method != "POST":
        form = DayForm()
    else:
        form = DayForm(data=request.POST)
        if form.is_valid():
            new_day = form.save(commit=False)
            new_day.cook = request.user
            meal = form.cleaned_data['meal']
            new_day.save()
            new_day.meal.add(meal[0])
            return HttpResponseRedirect(reverse('days'))
    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'planner/day_form.html', context)

class DayUpdate(LoginRequiredMixin, UpdateView):
    model = Day
    fields = ['date_meal', 'day_of_week', 'meal']

class DayDelete(LoginRequiredMixin, DeleteView):
    model = Day
    success_url = reverse_lazy('days')

# CRUD for Meal model
class MealCreate(LoginRequiredMixin, CreateView):
    model = Meal
    fields = ['name', 'ingredients', 'meal_type', 'meal_pic']

class MealUpdate(LoginRequiredMixin, UpdateView):
    model = Meal
    fields = ['name', 'ingredients', 'meal_type', 'meal_pic']

class MealDelete(LoginRequiredMixin, DeleteView):
    model = Meal
    success_url = reverse_lazy('meals')

planner/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Meal Planner</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="main-container">
      {% block sidebar %}
        <div class="sidebar-nav">
          <a class="sidebar-links" href="{% url 'index' %}">Home</a>
          <a class="sidebar-links" href="{% url 'days' %}">My Meal Plan</a>
          <a class="sidebar-links" href="{% url 'meals' %}">All Meals</a>
          <hr>
          
          {% if user.is_authenticated %}
            Cook: {{ user.get_username }}
            <a class="sidebar-links" href="{% url 'day-create' %}">Add a Day</a>
            <a class="sidebar-links" href="{% url 'meal-create' %}">Add a Meal</a>
            <a class="sidebar-links" href="{% url 'logout' %}?next={{request.path}}">Logout</a>
          {% else %}
            <a class="sidebar-links" href="{% url 'login' %}?next={{request.path}}">Login</a>
          {% endif %}
        </ul>
     {% endblock %}
      </div>

      <div class="content">
        {% block content %} {% endblock %}

        {% block pagination %}
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}"><button class="btn btn-info"><< Previous</button></a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}"><button class="btn btn-info">Next >></button></a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
    {% endblock %} 
      </div>
  </div>
</body>
</html>

planner/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Meal Planner</h1>
<p>Welcome Meal Planner, an app developed to make your dinner planning easy!</p>
Meals: {{ num_meals }}
{% endblock %}

planner/templates/planner/day_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Day</h1>

<p>Are you sure you want to delete the day: {{ day }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

planner/templates/planner/day_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Day Detail</h1>
    <div class='day-detail-content'>

    
        <h3>{{ day.get_day_of_week_display }}, {{ day.date_meal }}</h3>
        {% for meal in day.meal.all %}
            <img class="img-detail" src="{{ meal.meal_pic.url }}" class="img-responsive">
            <p><a href="{% url 'meal-detail' meal.pk %}">{{ meal }}</a></p>
            <p>{{ meal.ingredients }}</p>
            <p>{{ meal.get_meal_type_display }}</p>
        {% endfor %}

        <a href="{% url 'day-update' day.pk %}"><button type="button" class="btn btn-info">Edit Day</button></a>
        <a href="{% url 'day-delete' day.pk %}"><button type="button" class="btn btn-danger">Delete Day</button></a>
    </div>

{% endblock %}

planner/templates/planner/day_form.html
{% extends "base_generic.html" %}
{% load bootstrap4 %}  
        

{% block content %}
    {% bootstrap_css %} 
    {% bootstrap_javascript jquery='full' %} 
    <form action="" method="post">
        {% csrf_token %}
        {{ form.media }}  
        {% bootstrap_form form %}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

planner/templates/planner/day_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>This week's meal plan</h1>

    {% if day_list %}
    <div class="days-box">
        
            {% for day in day_list %}
                
                    <div class="single-day">
                        {% for meal in day.meal.all %}
                            <img src="{{ meal.meal_pic.url }}" class="img-responsive">
                            <p>{{ meal }}</p>
                        {% endfor %}
                        
                        <p>{{ day.get_day_of_week_display }}, {{ day.date_meal }}</p>

                        <div class="buttons">
                                <a href="{{ day.get_absolute_url }}">
                                    <button type="button" class="btn btn-info">See More</button>
                                </a>
                                <a href="{% url 'day-delete' day.pk %}"><button type="button" class="btn btn-danger">Delete Day</button></a>
                        </div>
                    </div>
                
            {% endfor %}
     
    </div>
    {% else %}
        <p>There are no days added yet.</p>
    {% endif %}

{% endblock %}

planner/templates/planner/meal_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Meal</h1>

<p>Are you sure you want to delete the meal: {{ meal }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

planner/templates/planner/meal_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Meal Details</h1>
    
    <img src="{{ meal.meal_pic.url }}" class="img-responsive">
    <p><strong>Meal:</strong> {{ meal }}</p>
    <p>{{ meal.ingredients }}</p>
    <p>{{ meal.get_meal_type_display }}</p>
    <p>You cooked this meal {{ meal.day_set.all.count }} time(s)  </p>
    <a href="{% url 'meal-update' meal.pk %}"><button type="button" class="btn btn-info">Edit Meal</button></a>
    <a href="{% url 'meal-delete' meal.pk %}"><button type="button" class="btn btn-danger">Delete Meal</button></a>


    
{% endblock %}

planner/templates/planner/meal_form.html
{% extends "base_generic.html" %}
{% load bootstrap4 %} 

{% block content %}
    <form enctype="multipart/form-data" action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

planner/templates/planner/meal_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Meal List</h1>

    {% if meal_list %}
        <div class="meal-container">
            {% for meal in meal_list %}

                    <a class="meal-info" href="{{ meal.get_absolute_url }}">
                        <img src="{{ meal.meal_pic.url }}" class="img-responsive">
                        {{ meal }}
                    </a>
                
            {% endfor %}
        </div>
    {% else %}
        <p>There are no meals added yet.</p>
    {% endif %}

{% endblock %}